[0m05:10:09.268505 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1ee7752b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1ec9fae70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1ec9faae0>]}


============================== 05:10:09.273550 | 980c8d0c-03de-46c2-a690-21c8c0aee7ff ==============================
[0m05:10:09.273550 [info ] [MainThread]: Running with dbt=1.9.3
[0m05:10:09.274065 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/josh/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --select optimized_table', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m05:10:09.274492 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/josh/heart-attack-prediction/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m05:10:09.275774 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.050550446, "process_in_blocks": "73744", "process_kernel_time": 0.272988, "process_mem_max_rss": "96428", "process_out_blocks": "8", "process_user_time": 0.945709}
[0m05:10:09.276103 [debug] [MainThread]: Command `dbt run` failed at 05:10:09.276029 after 0.05 seconds
[0m05:10:09.276353 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1f041b260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1ec75b9b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb1ec9bfad0>]}
[0m05:10:09.276606 [debug] [MainThread]: Flushing usage events
[0m05:10:10.453225 [debug] [MainThread]: An error was encountered while trying to flush usage events
